version: "3"
services:
  web:
    image: echowuhao/logbook:latest
    environment:
      DATABASE_URL: "postgresql://postgres:thisisapassword@db:5432/postgres"
    ports:
      - "5000:5000"
  db:
    image: postgres:14
    restart: always
    user: postgres
    environment:
      TZ: "Asia/Shanghai"
      PGTZ: "Asia/Shanghai"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "thisisapassword"
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-q",
          "-d",
          "postgres",
          "-U",
          "postgres"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
