// Code generated by sqlc. DO NOT EDIT.
// source: diary.sql


module Diary 

open Npgsql
open Npgsql.FSharp
open System
open System.Data




let addNote = """-- name: AddNote :one
INSERT INTO diary (note_id, user_id, note, last_updated) VALUES (@note_id, @user_id, @note, now())  
ON CONFLICT (note_id, user_id) DO UPDATE
SET note = EXCLUDED.note,
    last_updated = EXCLUDED.last_updated,
    -- Invalidate search index so background recovery can rebuild after restarts.
    search_text = '',
    search_terms = ARRAY[]::text[]
RETURNING id, user_id, note_id, note, search_text, search_terms, last_updated
"""


type AddNoteParams = {
  NoteId: string;
  UserId: int32;
  Note: string;
}

let AddNote (db: NpgsqlConnection)  (arg: AddNoteParams)  =
  
  let reader = fun (read:RowReader) -> {
    Id = read.int "id"
    UserId = read.int "user_id"
    NoteId = read.string "note_id"
    Note = read.string "note"
    SearchText = read.string "search_text"
    SearchTerms = read.stringArray "search_terms"
    LastUpdated = read.dateTime "last_updated"}
  

  db
  |> Sql.existingConnection
  |> Sql.query addNote
  |> Sql.parameters  [ "@note_id", Sql.string arg.NoteId; "@user_id", Sql.int arg.UserId; "@note", Sql.string arg.Note ]
  |> Sql.executeRow reader










let checkIdStale = """-- name: CheckIdStale :one
SELECT count(*)  > 0 as stale
FROM diary d
LEFT JOIN summary s ON d.note_id = s.note_id AND d.user_id = s.user_id
WHERE d.user_id = @user_id
  AND d.note_id = @note_id
  AND (s.id IS NULL OR d.last_updated > s.last_updated)
"""


type CheckIdStaleParams = {
  UserId: int32;
  NoteId: string;
}

let CheckIdStale (db: NpgsqlConnection)  (arg: CheckIdStaleParams)  =
  
  let reader = fun (read:RowReader) -> read.bool "stale"

  db
  |> Sql.existingConnection
  |> Sql.query checkIdStale
  |> Sql.parameters  [ "@user_id", Sql.int arg.UserId; "@note_id", Sql.string arg.NoteId ]
  |> Sql.executeRow reader












let createDiary = """-- name: CreateDiary :one
INSERT INTO diary (id, note) VALUES (@id, @note)
RETURNING id, user_id, note_id, note, search_text, search_terms, last_updated
"""


type CreateDiaryParams = {
  Id: int32;
  Note: string;
}

let CreateDiary (db: NpgsqlConnection)  (arg: CreateDiaryParams)  =
  
  let reader = fun (read:RowReader) -> {
    Id = read.int "id"
    UserId = read.int "user_id"
    NoteId = read.string "note_id"
    Note = read.string "note"
    SearchText = read.string "search_text"
    SearchTerms = read.stringArray "search_terms"
    LastUpdated = read.dateTime "last_updated"}
  

  db
  |> Sql.existingConnection
  |> Sql.query createDiary
  |> Sql.parameters  [ "@id", Sql.int arg.Id; "@note", Sql.string arg.Note ]
  |> Sql.executeRow reader













let deleteDiary = """-- name: DeleteDiary :exec
DELETE FROM diary WHERE id = @id
"""






let DeleteDiary (db: NpgsqlConnection)  (id: int32)  = 
  db 
  |> Sql.existingConnection
  |> Sql.query deleteDiary
  |> Sql.parameters  [ "@id", Sql.int id ]
  |> Sql.executeNonQuery








let diaryByID = """-- name: DiaryByID :one
SELECT id, user_id, note_id, note, search_text, search_terms, last_updated FROM diary WHERE id = @id
"""



let DiaryByID (db: NpgsqlConnection)  (id: int32)  =
  
  let reader = fun (read:RowReader) -> {
    Id = read.int "id"
    UserId = read.int "user_id"
    NoteId = read.string "note_id"
    Note = read.string "note"
    SearchText = read.string "search_text"
    SearchTerms = read.stringArray "search_terms"
    LastUpdated = read.dateTime "last_updated"}
  

  db
  |> Sql.existingConnection
  |> Sql.query diaryByID
  |> Sql.parameters  [ "@id", Sql.int id ]
  |> Sql.executeRow reader










let diaryByUserIDAndID = """-- name: DiaryByUserIDAndID :one
SELECT id, user_id, note_id, note, search_text, search_terms, last_updated FROM diary WHERE user_id = @user_id and note_id=@note_id
"""


type DiaryByUserIDAndIDParams = {
  UserId: int32;
  NoteId: string;
}

let DiaryByUserIDAndID (db: NpgsqlConnection)  (arg: DiaryByUserIDAndIDParams)  =
  
  let reader = fun (read:RowReader) -> {
    Id = read.int "id"
    UserId = read.int "user_id"
    NoteId = read.string "note_id"
    Note = read.string "note"
    SearchText = read.string "search_text"
    SearchTerms = read.stringArray "search_terms"
    LastUpdated = read.dateTime "last_updated"}
  

  db
  |> Sql.existingConnection
  |> Sql.query diaryByUserIDAndID
  |> Sql.parameters  [ "@user_id", Sql.int arg.UserId; "@note_id", Sql.string arg.NoteId ]
  |> Sql.executeRow reader














let getStaleIdsOfUserId = """-- name: GetStaleIdsOfUserId :many
SELECT d.id, d.user_id, d.note_id, d.note, d.search_text, d.search_terms, d.last_updated
FROM diary d
LEFT JOIN summary s ON d.note_id = s.note_id AND d.user_id = s.user_id
WHERE (s.id IS NULL OR d.last_updated > s.last_updated) AND d.user_id = @user_id
"""




let GetStaleIdsOfUserId (db: NpgsqlConnection)  (userId: int32) =
  let reader = fun (read:RowReader) -> {
    Id = read.int "id"
    UserId = read.int "user_id"
    NoteId = read.string "note_id"
    Note = read.string "note"
    SearchText = read.string "search_text"
    SearchTerms = read.stringArray "search_terms"
    LastUpdated = read.dateTime "last_updated"}
  
  db 
  |> Sql.existingConnection
  |> Sql.query getStaleIdsOfUserId
  |> Sql.parameters  [ "@user_id", Sql.int userId ]
  |> Sql.execute reader


















let listDiaries = """-- name: ListDiaries :many
SELECT id, user_id, note_id, note, search_text, search_terms, last_updated FROM diary ORDER BY last_updated DESC
"""




let ListDiaries (db: NpgsqlConnection)  =
  let reader = fun (read:RowReader) -> {
    Id = read.int "id"
    UserId = read.int "user_id"
    NoteId = read.string "note_id"
    Note = read.string "note"
    SearchText = read.string "search_text"
    SearchTerms = read.stringArray "search_terms"
    LastUpdated = read.dateTime "last_updated"}
  
  db 
  |> Sql.existingConnection
  |> Sql.query listDiaries
  |> Sql.execute reader








let listDiaryByUserID = """-- name: ListDiaryByUserID :many
SELECT id, user_id, note_id, note, search_text, search_terms, last_updated FROM diary WHERE user_id = @user_id order by note_id DESC
"""




let ListDiaryByUserID (db: NpgsqlConnection)  (userId: int32) =
  let reader = fun (read:RowReader) -> {
    Id = read.int "id"
    UserId = read.int "user_id"
    NoteId = read.string "note_id"
    Note = read.string "note"
    SearchText = read.string "search_text"
    SearchTerms = read.stringArray "search_terms"
    LastUpdated = read.dateTime "last_updated"}
  
  db 
  |> Sql.existingConnection
  |> Sql.query listDiaryByUserID
  |> Sql.parameters  [ "@user_id", Sql.int userId ]
  |> Sql.execute reader








let listDiaryIDByUserID = """-- name: ListDiaryIDByUserID :many
SELECT note_id FROM diary WHERE user_id = @user_id AND note != '' order by note_id DESC
"""




let ListDiaryIDByUserID (db: NpgsqlConnection)  (userId: int32) =
  let reader = fun (read:RowReader) -> read.string "note_id"
  
  db 
  |> Sql.existingConnection
  |> Sql.query listDiaryIDByUserID
  |> Sql.parameters  [ "@user_id", Sql.int userId ]
  |> Sql.execute reader








let listDiaryWithTodo = """-- name: ListDiaryWithTodo :many
SELECT id, user_id, note_id, note, search_text, search_terms, last_updated
FROM diary
WHERE note != ''
  AND (
    note LIKE '%todo_list%'
    OR note LIKE '%todo_item%'
    OR note LIKE '%taskList%'
    OR note LIKE '%taskItem%'
  )
ORDER BY user_id, note_id DESC
"""




let ListDiaryWithTodo (db: NpgsqlConnection)  =
  let reader = fun (read:RowReader) -> {
    Id = read.int "id"
    UserId = read.int "user_id"
    NoteId = read.string "note_id"
    Note = read.string "note"
    SearchText = read.string "search_text"
    SearchTerms = read.stringArray "search_terms"
    LastUpdated = read.dateTime "last_updated"}
  
  db 
  |> Sql.existingConnection
  |> Sql.query listDiaryWithTodo
  |> Sql.execute reader








let listDiaryWithTodoByUserID = """-- name: ListDiaryWithTodoByUserID :many
SELECT id, user_id, note_id, note, search_text, search_terms, last_updated
FROM diary
WHERE user_id = @user_id
  AND note != ''
  AND (
    note LIKE '%todo_list%'
    OR note LIKE '%todo_item%'
    OR note LIKE '%taskList%'
    OR note LIKE '%taskItem%'
  )
ORDER BY note_id DESC
"""




let ListDiaryWithTodoByUserID (db: NpgsqlConnection)  (userId: int32) =
  let reader = fun (read:RowReader) -> {
    Id = read.int "id"
    UserId = read.int "user_id"
    NoteId = read.string "note_id"
    Note = read.string "note"
    SearchText = read.string "search_text"
    SearchTerms = read.stringArray "search_terms"
    LastUpdated = read.dateTime "last_updated"}
  
  db 
  |> Sql.existingConnection
  |> Sql.query listDiaryWithTodoByUserID
  |> Sql.parameters  [ "@user_id", Sql.int userId ]
  |> Sql.execute reader








let listMissingSearchIndex = """-- name: ListMissingSearchIndex :many
SELECT id, user_id, note_id, note, search_text, search_terms, last_updated
FROM diary
WHERE note != '' AND (search_text = '' OR search_terms = ARRAY[]::text[])
"""




let ListMissingSearchIndex (db: NpgsqlConnection)  =
  let reader = fun (read:RowReader) -> {
    Id = read.int "id"
    UserId = read.int "user_id"
    NoteId = read.string "note_id"
    Note = read.string "note"
    SearchText = read.string "search_text"
    SearchTerms = read.stringArray "search_terms"
    LastUpdated = read.dateTime "last_updated"}
  
  db 
  |> Sql.existingConnection
  |> Sql.query listMissingSearchIndex
  |> Sql.execute reader








let listStaleSummaryIds = """-- name: ListStaleSummaryIds :many
SELECT d.id, d.user_id, d.note_id, d.note, d.search_text, d.search_terms, d.last_updated
FROM diary d
LEFT JOIN summary s ON d.note_id = s.note_id AND d.user_id = s.user_id
WHERE s.id IS NULL OR d.last_updated > s.last_updated
"""




let ListStaleSummaryIds (db: NpgsqlConnection)  =
  let reader = fun (read:RowReader) -> {
    Id = read.int "id"
    UserId = read.int "user_id"
    NoteId = read.string "note_id"
    Note = read.string "note"
    SearchText = read.string "search_text"
    SearchTerms = read.stringArray "search_terms"
    LastUpdated = read.dateTime "last_updated"}
  
  db 
  |> Sql.existingConnection
  |> Sql.query listStaleSummaryIds
  |> Sql.execute reader








let searchDiary = """-- name: SearchDiary :many
WITH query_terms AS (
  SELECT
    CASE
      WHEN @query_terms = '' THEN ARRAY[]::text[]
      ELSE string_to_array(@query_terms, @separator)
    END AS terms
)
SELECT d.note_id, d.search_text, d.last_updated,
       (
         SELECT COUNT(*)
         FROM unnest(d.search_terms) term
         WHERE term = ANY(query_terms.terms)
       )::int AS rank
FROM diary d
CROSS JOIN query_terms
WHERE d.user_id = @user_id
  AND d.search_terms && query_terms.terms
ORDER BY rank DESC, d.last_updated DESC, d.note_id DESC
"""


type SearchDiaryParams = {
  UserId: int32;
  QueryTerms: string option;
  Separator: string;
}
type SearchDiaryRow = {
  NoteId: string;
  SearchText: string;
  LastUpdated: DateTime;
  Rank: int32;
}


let SearchDiary (db: NpgsqlConnection)  (arg: SearchDiaryParams) =
  let reader = fun (read:RowReader) -> {
    NoteId = read.string "note_id"
    SearchText = read.string "search_text"
    LastUpdated = read.dateTime "last_updated"
    Rank = read.int "rank"}
  
  db 
  |> Sql.existingConnection
  |> Sql.query searchDiary
  |> Sql.parameters  [ "@user_id", Sql.int arg.UserId; "@query_terms", Sql.stringOrNone arg.QueryTerms; "@separator", Sql.string arg.Separator ]
  |> Sql.execute reader










let updateDiary = """-- name: UpdateDiary :one
UPDATE diary SET note = @note, last_updated = NOW() WHERE id = @id
RETURNING id, user_id, note_id, note, search_text, search_terms, last_updated
"""


type UpdateDiaryParams = {
  Id: int32;
  Note: string;
}

let UpdateDiary (db: NpgsqlConnection)  (arg: UpdateDiaryParams)  =
  
  let reader = fun (read:RowReader) -> {
    Id = read.int "id"
    UserId = read.int "user_id"
    NoteId = read.string "note_id"
    Note = read.string "note"
    SearchText = read.string "search_text"
    SearchTerms = read.stringArray "search_terms"
    LastUpdated = read.dateTime "last_updated"}
  

  db
  |> Sql.existingConnection
  |> Sql.query updateDiary
  |> Sql.parameters  [ "@id", Sql.int arg.Id; "@note", Sql.string arg.Note ]
  |> Sql.executeRow reader










let updateDiarySearch = """-- name: UpdateDiarySearch :exec
UPDATE diary
SET search_text = @search_text,
    search_terms =
        CASE
            WHEN @search_terms = '' THEN ARRAY[]::text[]
            ELSE string_to_array(@search_terms, @separator)
        END
WHERE note_id = @note_id AND user_id = @user_id
"""


type UpdateDiarySearchParams = {
  NoteId: string;
  UserId: int32;
  SearchText: string;
  SearchTerms: string option;
  Separator: string;
}




let UpdateDiarySearch (db: NpgsqlConnection)  (arg: UpdateDiarySearchParams)  = 
  db 
  |> Sql.existingConnection
  |> Sql.query updateDiarySearch
  |> Sql.parameters  [ "@note_id", Sql.string arg.NoteId; "@user_id", Sql.int arg.UserId; "@search_text", Sql.string arg.SearchText; "@search_terms", Sql.stringOrNone arg.SearchTerms; "@separator", Sql.string arg.Separator ]
  |> Sql.executeNonQuery







