// Code generated by sqlc. DO NOT EDIT.
// source: todo.sql

module Todo

open Npgsql
open Npgsql.FSharp

let deleteTodo = """-- name: DeleteTodo :exec
DELETE FROM todo WHERE note_id = @note_id AND user_id = @user_id
"""

type DeleteTodoParams = {
  NoteId: string;
  UserId: int32;
}

let DeleteTodo (db: NpgsqlConnection) (arg: DeleteTodoParams) =
  db
  |> Sql.existingConnection
  |> Sql.query deleteTodo
  |> Sql.parameters [ "@note_id", Sql.string arg.NoteId; "@user_id", Sql.int arg.UserId ]
  |> Sql.executeNonQuery

let getTodoByUserId = """-- name: GetTodoByUserId :many
SELECT note_id, todos FROM todo WHERE user_id = @user_id ORDER BY note_id DESC
"""

type GetTodoByUserIdRow = {
  NoteId: string;
  Todos: string;
}

let GetTodoByUserId (db: NpgsqlConnection) (userId: int32) =
  let reader = fun (read: RowReader) -> {
    NoteId = read.string "note_id"
    Todos = read.string "todos" }

  db
  |> Sql.existingConnection
  |> Sql.query getTodoByUserId
  |> Sql.parameters [ "@user_id", Sql.int userId ]
  |> Sql.execute reader

let insertOrUpdateTodo = """-- name: InsertOrUpdateTodo :exec
INSERT INTO todo (note_id, user_id, todos)
VALUES (@note_id, @user_id, @todos)
ON CONFLICT (note_id, user_id) DO UPDATE SET todos = EXCLUDED.todos
"""

type InsertOrUpdateTodoParams = {
  NoteId: string;
  UserId: int32;
  Todos: string;
}

let InsertOrUpdateTodo (db: NpgsqlConnection) (arg: InsertOrUpdateTodoParams) =
  db
  |> Sql.existingConnection
  |> Sql.query insertOrUpdateTodo
  |> Sql.parameters [ "@note_id", Sql.string arg.NoteId; "@user_id", Sql.int arg.UserId; "@todos", Sql.jsonb arg.Todos ]
  |> Sql.executeNonQuery
