// Code generated by sqlc. DO NOT EDIT.

[<AutoOpen>]
module ModelFromSchema 
        
open System


type AuthUser = {
     Id: int32
     Password: string
     LastLogin: DateTime
     IsSuperuser: bool
     Username: string
     FirstName: string
     LastName: string
     Email: string
     IsStaff: bool
     IsActive: bool
     DateJoined: DateTime
}

type Diary = {
     Id: string
     UserId: int32
     Note: string
     LastUpdated: DateTime
}

type JwtSecret = {
     Id: int32
     Name: string
     Secret: string
     Audience: string
}

type Summary = {
     Id: string
     UserId: int32
     CreatedAt: DateTime
     LastUpdated: DateTime
     Content: string
}


