// Code generated by sqlc. DO NOT EDIT.

[<AutoOpen>]
module ModelFromSchema 
        
open System


type Diary = {
     Id: string
     Note: string
     LastUpdated: DateTime
}

type Summary = {
     Id: string
     CreatedAt: DateTime
     LastUpdated: DateTime
     Content: string
}


