// Code generated by sqlc. DO NOT EDIT.
// source: summary.sql


module Summary 

open Npgsql
open Npgsql.FSharp
open System

















let getSummaryByUserIDAndID = """-- name: GetSummaryByUserIDAndID :one
SELECT id, user_id, created_at, last_updated, content FROM summary WHERE user_id = @user_id and id=@id
"""


type GetSummaryByUserIDAndIDParams = {
  UserId: int32;
  Id: string;
}

let GetSummaryByUserIDAndID (db: NpgsqlConnection)  (arg: GetSummaryByUserIDAndIDParams)  =
  
  let reader = fun (read:RowReader) -> {
    Id = read.string "id"
    UserId = read.int "user_id"
    CreatedAt = read.dateTime "created_at"
    LastUpdated = read.dateTime "last_updated"
    Content = read.string "content"}
  

  db
  |> Sql.existingConnection
  |> Sql.query getSummaryByUserIDAndID
  |> Sql.parameters  [ "@user_id", Sql.int arg.UserId; "@id", Sql.string arg.Id ]
  |> Sql.executeRow reader












let getSummaryByUserId = """-- name: GetSummaryByUserId :many
select id, content as note from summary where user_id = @user_id order by id desc
"""


type GetSummaryByUserIdRow = {
  Id: string;
  Note: string;
}


let GetSummaryByUserId (db: NpgsqlConnection)  (userId: int32) =
  let reader = fun (read:RowReader) -> {
    Id = read.string "id"
    Note = read.string "note"}
  db 
  |> Sql.existingConnection
  |> Sql.query getSummaryByUserId
  |> Sql.parameters  [ "@user_id", Sql.int userId ]
  |> Sql.execute reader




















