name: build allin one image

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"
env:
  PG_DB: postgres
  PG_USER: postgres
  PG_HOST: localhost
  PG_PASS: thisisapassword

jobs:
  build_logbook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: build web
        run: |
          npm install
          npm run build
        working-directory: web
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: api
      - name: Build logbook image
        run: |
          docker build . --file Dockerfile -t ghcr.io/swuecho/logbook:${GITHUB_SHA}
        working-directory: api

