---
kind: pipeline
type: exec
name: default_test

steps:
  - name: build 
    commands:
      - uname -a
      - docker build -t 192.168.0.100:5555/notepad_frontend:latest -f Dockerfile .
      - docker push 192.168.0.100:5555/notepad_frontend:latest
...